// Realistic sample dataset — used ONLY by the explicit "Load Demo Data"
// action (see src/lib/data/demo-data.ts + the Settings/empty-dashboard
// entry points). Never seeded automatically: a real account starts
// with zero resources, zero stacks, zero tags.
import type { Category, Resource, Stack, Tag } from "./types";
import { categories as defaultTaxonomy } from "./categories";

// Demo resources reference the default taxonomy's old slug-style ids
// (e.g. "dev-frontend") — resolve each to whichever real category this
// user's own "Frontend" (under "Development") row actually has. If they've
// renamed or deleted it, the resource just gets no category rather than
// resurrecting a category the user chose to get rid of. Pure — used by
// src/lib/data/demo-data.ts, exported here (a dependency-free module) so
// it's unit-testable without a database.
export function resolveDefaultCategoryId(slug: string, userCategories: Category[]): string | null {
  const ref = defaultTaxonomy.find((c) => c.id === slug);
  if (!ref) return null;
  const parentRef = ref.parentId ? defaultTaxonomy.find((c) => c.id === ref.parentId) : null;
  const match = userCategories.find((c) => {
    if (c.name.toLowerCase() !== ref.name.toLowerCase()) return false;
    if (!parentRef) return c.parentId === null;
    const parent = userCategories.find((p) => p.id === c.parentId);
    return parent?.name.toLowerCase() === parentRef.name.toLowerCase();
  });
  return match?.id ?? null;
}

const daysAgo = (n: number, hourOffset = 9) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hourOffset, 0, 0, 0);
  return d.toISOString();
};

export const tags: Tag[] = [
  "react", "nextjs", "vite", "tailwind", "css", "svg", "images", "webp", "compression",
  "api", "graphql", "rest", "testing", "jwt", "database", "postgres", "prisma", "redis",
  "ai", "llm", "self-hosted", "cli", "docker", "kubernetes", "ci-cd", "design", "icons",
  "fonts", "regex", "json", "markdown", "typescript", "node", "performance", "accessibility",
  "animation", "components", "auth", "email", "monitoring", "git",
].map((name) => ({ id: name, name }));

export const stacks: Stack[] = [
  {
    id: "frontend",
    name: "Frontend",
    description: "Everything I use for building modern web interfaces.",
    icon: "🌐",
    color: "accent",
    createdAt: daysAgo(180),
  },
  {
    id: "ai-ml",
    name: "AI & ML",
    description: "Models, inference tools, and frameworks for AI features.",
    icon: "🤖",
    color: "violet",
    createdAt: daysAgo(150),
  },
  {
    id: "backend",
    name: "Backend",
    description: "Services, databases, and APIs behind the apps I build.",
    icon: "⚙️",
    color: "cyan",
    createdAt: daysAgo(170),
  },
  {
    id: "design-ux",
    name: "Design & UX",
    description: "Visual tools, assets, and references for interface design.",
    icon: "🎨",
    color: "warning",
    createdAt: daysAgo(140),
  },
  {
    id: "devops",
    name: "DevOps",
    description: "Deploying, monitoring, and shipping without surprises.",
    icon: "☁️",
    color: "success",
    createdAt: daysAgo(120),
  },
  {
    id: "utilities-stack",
    name: "Utilities",
    description: "Small tools I reach for constantly.",
    icon: "🛠️",
    color: "accent",
    createdAt: daysAgo(200),
  },
  {
    id: "personal-projects",
    name: "Personal Projects",
    description: "The stack I default to for side projects.",
    icon: "🧪",
    color: "violet",
    createdAt: daysAgo(90),
  },
];

interface Seed {
  title: string;
  url: string;
  description: string;
  categoryId: string;
  useCases: string[];
  notes: string;
  tagIds: string[];
  stackIds: string[];
  pricing: Resource["pricing"];
  platform: Resource["platform"];
  createdDaysAgo: number;
  favorite?: boolean;
  archived?: boolean;
  useCount?: number;
}

const seeds: Seed[] = [
  {
    title: "Squoosh",
    url: "https://squoosh.app",
    description: "Compress and optimize images directly in your browser.",
    categoryId: "dev-web-images",
    useCases: ["Compress images", "Convert to WebP", "Convert to AVIF", "Optimize images for websites"],
    notes: "Use this when images are too large before adding them to a website. WebP at 75-80% quality is usually the sweet spot.",
    tagIds: ["webp", "images", "compression", "performance"],
    stackIds: ["frontend", "design-ux"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 2,
    favorite: true,
    useCount: 14,
  },
  {
    title: "Bruno",
    url: "https://usebruno.com",
    description: "Fast, offline-first, Git-friendly API client for testing REST and GraphQL.",
    categoryId: "dev-api",
    useCases: ["Test REST APIs", "Test GraphQL endpoints", "Debug API requests", "Store collections in Git"],
    notes: "Lightweight alternative to Postman. Collections live in the repo as .bru files instead of a cloud account.",
    tagIds: ["api", "graphql", "rest", "testing", "git"],
    stackIds: ["backend", "utilities-stack"],
    pricing: "open-source",
    platform: ["desktop"],
    createdDaysAgo: 5,
    favorite: true,
    useCount: 22,
  },
  {
    title: "SVGR",
    url: "https://react-svgr.com",
    description: "Convert SVG files into ready-to-use React JSX components.",
    categoryId: "dev-frontend",
    useCases: ["Convert SVG to React", "Generate icon components", "Automate icon pipelines"],
    notes: "Solves the 'turn this SVG into a component' problem instantly, no manual path editing.",
    tagIds: ["svg", "react", "icons"],
    stackIds: ["frontend", "personal-projects"],
    pricing: "open-source",
    platform: ["web", "cli"],
    createdDaysAgo: 8,
    useCount: 9,
  },
  {
    title: "React",
    url: "https://react.dev",
    description: "A JavaScript library for building user interfaces with components.",
    categoryId: "dev-frontend",
    useCases: ["Build UI components", "Manage client-side state", "Server components & streaming"],
    notes: "Default choice for anything with real interactivity.",
    tagIds: ["react", "components", "typescript"],
    stackIds: ["frontend", "personal-projects"],
    pricing: "open-source",
    platform: ["web"],
    createdDaysAgo: 300,
    favorite: true,
    useCount: 61,
  },
  {
    title: "Next.js",
    url: "https://nextjs.org",
    description: "The React framework for production: routing, rendering, and APIs.",
    categoryId: "dev-frontend",
    useCases: ["Server-render React apps", "File-based routing", "Build full-stack apps", "Edge & API routes"],
    notes: "Go-to for anything that needs SEO or a backend next to the frontend.",
    tagIds: ["react", "nextjs", "typescript"],
    stackIds: ["frontend", "personal-projects"],
    pricing: "open-source",
    platform: ["web", "cli"],
    createdDaysAgo: 250,
    useCount: 48,
  },
  {
    title: "Vite",
    url: "https://vite.dev",
    description: "A fast build tool and dev server with instant hot module replacement.",
    categoryId: "dev-frontend",
    useCases: ["Bundle a frontend app", "Instant dev server", "Fast HMR during development"],
    notes: "",
    tagIds: ["vite", "performance"],
    stackIds: ["frontend"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 260,
    useCount: 33,
  },
  {
    title: "Tailwind CSS",
    url: "https://tailwindcss.com",
    description: "A utility-first CSS framework for building custom designs quickly.",
    categoryId: "dev-frontend",
    useCases: ["Style components with utility classes", "Build design systems", "Responsive layouts"],
    notes: "Fast for prototyping, keeps CSS out of separate files.",
    tagIds: ["css", "tailwind"],
    stackIds: ["frontend", "personal-projects"],
    pricing: "open-source",
    platform: ["web"],
    createdDaysAgo: 270,
    favorite: true,
    useCount: 55,
  },
  {
    title: "shadcn/ui",
    url: "https://ui.shadcn.com",
    description: "Accessible, unstyled Radix components you copy into your codebase.",
    categoryId: "dev-frontend",
    useCases: ["Build accessible components fast", "Own the component code, not a dependency", "Style with Tailwind"],
    notes: "Not a package — components get copied in, so they're fully editable.",
    tagIds: ["react", "components", "accessibility"],
    stackIds: ["frontend"],
    pricing: "open-source",
    platform: ["web"],
    createdDaysAgo: 90,
    useCount: 27,
  },
  {
    title: "Framer Motion",
    url: "https://motion.dev",
    description: "A production-ready animation library for React.",
    categoryId: "dev-frontend",
    useCases: ["Animate UI transitions", "Gesture-based interactions", "Layout animations"],
    notes: "Reach for this when CSS transitions aren't enough.",
    tagIds: ["react", "animation"],
    stackIds: ["frontend"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 40,
    useCount: 11,
  },
  {
    title: "Postman",
    url: "https://postman.com",
    description: "A full-featured platform for building and testing APIs.",
    categoryId: "dev-api",
    useCases: ["Test REST APIs", "Automate API test collections", "Mock servers"],
    notes: "Heavier than Bruno but useful when a team is already using Postman workspaces.",
    tagIds: ["api", "rest", "testing"],
    stackIds: ["backend"],
    pricing: "freemium",
    platform: ["desktop", "web"],
    createdDaysAgo: 320,
    useCount: 19,
  },
  {
    title: "Insomnia",
    url: "https://insomnia.rest",
    description: "An API client for designing and debugging REST and GraphQL APIs.",
    categoryId: "dev-api",
    useCases: ["Test GraphQL endpoints", "Design REST APIs", "Debug requests with environments"],
    notes: "",
    tagIds: ["api", "graphql", "rest"],
    stackIds: ["backend"],
    pricing: "freemium",
    platform: ["desktop"],
    createdDaysAgo: 100,
    useCount: 6,
  },
  {
    title: "Node.js",
    url: "https://nodejs.org",
    description: "A JavaScript runtime built on Chrome's V8 engine for server-side code.",
    categoryId: "dev-backend",
    useCases: ["Run JavaScript on the server", "Build CLIs", "Power build tooling"],
    notes: "",
    tagIds: ["node"],
    stackIds: ["backend", "personal-projects"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 400,
    useCount: 70,
  },
  {
    title: "PostgreSQL",
    url: "https://postgresql.org",
    description: "A powerful open-source object-relational database system.",
    categoryId: "dev-database",
    useCases: ["Store relational data", "Full-text search", "JSON columns for flexible data"],
    notes: "Default database for anything that isn't a prototype.",
    tagIds: ["database", "postgres"],
    stackIds: ["backend", "personal-projects"],
    pricing: "open-source",
    platform: ["cli", "desktop"],
    createdDaysAgo: 350,
    favorite: true,
    useCount: 44,
  },
  {
    title: "Prisma",
    url: "https://prisma.io",
    description: "A type-safe ORM and query builder for Node.js and TypeScript.",
    categoryId: "dev-database",
    useCases: ["Query a database with types", "Manage schema migrations", "Format schema files"],
    notes: "The `prisma format` command is what I actually search for most.",
    tagIds: ["database", "prisma", "typescript"],
    stackIds: ["backend", "personal-projects"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 60,
    useCount: 25,
  },
  {
    title: "Redis",
    url: "https://redis.io",
    description: "An in-memory data store used for caching, queues, and pub/sub.",
    categoryId: "dev-database",
    useCases: ["Cache expensive queries", "Rate limiting", "Job queues"],
    notes: "",
    tagIds: ["database", "redis", "performance"],
    stackIds: ["backend"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 130,
    useCount: 14,
  },
  {
    title: "TablePlus",
    url: "https://tableplus.com",
    description: "A modern, native GUI for managing relational databases.",
    categoryId: "dev-database",
    useCases: ["Browse database tables visually", "Run and save SQL queries", "Inspect schema relationships"],
    notes: "The database visualizer I actually open every day.",
    tagIds: ["database", "postgres"],
    stackIds: ["backend"],
    pricing: "freemium",
    platform: ["desktop"],
    createdDaysAgo: 20,
    useCount: 17,
  },
  {
    title: "Docker",
    url: "https://docker.com",
    description: "A platform for building, shipping, and running containerized apps.",
    categoryId: "dev-devops",
    useCases: ["Containerize an app", "Run local dev environments", "Ship consistent builds"],
    notes: "",
    tagIds: ["docker", "ci-cd"],
    stackIds: ["devops"],
    pricing: "freemium",
    platform: ["desktop", "cli"],
    createdDaysAgo: 200,
    useCount: 30,
  },
  {
    title: "GitHub Actions",
    url: "https://github.com/features/actions",
    description: "CI/CD workflows that run directly from a GitHub repository.",
    categoryId: "dev-devops",
    useCases: ["Run tests on every push", "Automate deployments", "Build release pipelines"],
    notes: "",
    tagIds: ["ci-cd", "git"],
    stackIds: ["devops"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 210,
    useCount: 21,
  },
  {
    title: "Vercel",
    url: "https://vercel.com",
    description: "Deployment platform for frontend frameworks with instant previews.",
    categoryId: "dev-devops",
    useCases: ["Deploy a Next.js app", "Preview deployments per PR", "Edge functions"],
    notes: "",
    tagIds: ["ci-cd", "nextjs"],
    stackIds: ["devops", "personal-projects"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 220,
    useCount: 26,
  },
  {
    title: "Sentry",
    url: "https://sentry.io",
    description: "Application monitoring for tracking errors and performance issues.",
    categoryId: "dev-devops",
    useCases: ["Track production errors", "Monitor performance regressions", "Alert on new issues"],
    notes: "",
    tagIds: ["monitoring"],
    stackIds: ["devops"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 15,
    useCount: 8,
  },
  {
    title: "OpenAI Platform",
    url: "https://platform.openai.com",
    description: "APIs for GPT models, embeddings, and multimodal AI features.",
    categoryId: "ai-models",
    useCases: ["Add AI chat features", "Generate embeddings for search", "Summarize or classify text"],
    notes: "",
    tagIds: ["ai", "llm", "api"],
    stackIds: ["ai-ml"],
    pricing: "paid",
    platform: ["web"],
    createdDaysAgo: 90,
    favorite: true,
    useCount: 34,
  },
  {
    title: "Hugging Face",
    url: "https://huggingface.co",
    description: "A hub for open-source models, datasets, and inference tools.",
    categoryId: "ai-models",
    useCases: ["Find open-source models", "Host and share datasets", "Run inference in the browser"],
    notes: "",
    tagIds: ["ai", "llm"],
    stackIds: ["ai-ml"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 75,
    useCount: 12,
  },
  {
    title: "LangChain",
    url: "https://langchain.com",
    description: "A framework for building applications powered by language models.",
    categoryId: "ai-frameworks",
    useCases: ["Chain LLM calls together", "Build retrieval-augmented generation", "Manage prompt templates"],
    notes: "Useful for prototyping, tends to get swapped out once the app matures.",
    tagIds: ["ai", "llm"],
    stackIds: ["ai-ml"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 55,
    useCount: 7,
  },
  {
    title: "Ollama",
    url: "https://ollama.com",
    description: "Run open-source large language models locally on your machine.",
    categoryId: "ai-models",
    useCases: ["Run LLMs locally", "Test models offline", "Self-host inference"],
    notes: "Good for testing prompts without burning API credits.",
    tagIds: ["ai", "llm", "self-hosted"],
    stackIds: ["ai-ml", "personal-projects"],
    pricing: "open-source",
    platform: ["cli", "desktop"],
    createdDaysAgo: 30,
    favorite: true,
    useCount: 18,
  },
  {
    title: "Figma",
    url: "https://figma.com",
    description: "A collaborative interface design tool with real-time editing.",
    categoryId: "design-ui",
    useCases: ["Design UI screens", "Build design systems", "Prototype interactions"],
    notes: "",
    tagIds: ["design"],
    stackIds: ["design-ux"],
    pricing: "freemium",
    platform: ["web", "desktop"],
    createdDaysAgo: 500,
    favorite: true,
    useCount: 40,
  },
  {
    title: "Ray.so",
    url: "https://ray.so",
    description: "Create beautiful, shareable images of code snippets.",
    categoryId: "design-assets",
    useCases: ["Make code screenshots for docs", "Share snippets on social media"],
    notes: "",
    tagIds: ["design"],
    stackIds: ["design-ux", "utilities-stack"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 12,
    useCount: 5,
  },
  {
    title: "Lucide Icons",
    url: "https://lucide.dev",
    description: "A consistent, open-source icon set with React and Vue packages.",
    categoryId: "design-assets",
    useCases: ["Find UI icons", "Import icons as React components"],
    notes: "",
    tagIds: ["icons", "react"],
    stackIds: ["design-ux", "frontend"],
    pricing: "open-source",
    platform: ["web"],
    createdDaysAgo: 45,
    useCount: 20,
  },
  {
    title: "Fontsource",
    url: "https://fontsource.org",
    description: "Self-hostable, npm-packaged web fonts for any framework.",
    categoryId: "design-assets",
    useCases: ["Self-host web fonts", "Avoid third-party font CDNs"],
    notes: "",
    tagIds: ["fonts", "performance"],
    stackIds: ["design-ux"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 65,
    useCount: 4,
  },
  {
    title: "jwt.io",
    url: "https://jwt.io",
    description: "Decode, verify, and inspect JSON Web Tokens in the browser.",
    categoryId: "utilities-formatters",
    useCases: ["Decode a JWT", "Verify token signatures", "Debug auth issues"],
    notes: "First stop whenever an auth token looks wrong.",
    tagIds: ["jwt", "auth"],
    stackIds: ["utilities-stack", "backend"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 3,
    favorite: true,
    useCount: 16,
  },
  {
    title: "JSON Crack",
    url: "https://jsoncrack.com",
    description: "Visualize JSON, YAML, and XML data as interactive graphs.",
    categoryId: "utilities-formatters",
    useCases: ["Visualize nested JSON", "Explore API responses", "Convert JSON to other formats"],
    notes: "",
    tagIds: ["json"],
    stackIds: ["utilities-stack"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 25,
    useCount: 9,
  },
  {
    title: "regex101",
    url: "https://regex101.com",
    description: "Build, test, and debug regular expressions with live explanations.",
    categoryId: "utilities-formatters",
    useCases: ["Test a regex pattern", "Debug a regex match", "Learn what a pattern does"],
    notes: "",
    tagIds: ["regex"],
    stackIds: ["utilities-stack"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 1,
    useCount: 23,
  },
  {
    title: "TinyPNG",
    url: "https://tinypng.com",
    description: "Smart lossy compression for PNG and JPEG images.",
    categoryId: "dev-web-images",
    useCases: ["Compress PNG images", "Compress JPEG images", "Reduce image file size"],
    notes: "",
    tagIds: ["images", "compression"],
    stackIds: ["design-ux"],
    pricing: "freemium",
    platform: ["web"],
    createdDaysAgo: 4,
    useCount: 10,
  },
  {
    title: "ImageOptim",
    url: "https://imageoptim.com",
    description: "A drag-and-drop app to strip unnecessary image metadata and compress.",
    categoryId: "dev-web-images",
    useCases: ["Batch compress images", "Strip image metadata"],
    notes: "",
    tagIds: ["images", "compression"],
    stackIds: ["design-ux"],
    pricing: "free",
    platform: ["desktop"],
    createdDaysAgo: 110,
    useCount: 6,
    archived: true,
  },
  {
    title: "SVGO",
    url: "https://github.com/svg/svgo",
    description: "A Node.js tool for optimizing SVG vector graphics files.",
    categoryId: "dev-web-images",
    useCases: ["Minify SVG files", "Strip unused SVG metadata"],
    notes: "",
    tagIds: ["svg", "compression"],
    stackIds: ["frontend"],
    pricing: "open-source",
    platform: ["cli"],
    createdDaysAgo: 140,
    useCount: 8,
  },
  {
    title: "CleanShot X",
    url: "https://cleanshot.com",
    description: "A screenshot and screen recording tool with annotation built in.",
    categoryId: "utilities-formatters",
    useCases: ["Take annotated screenshots", "Record short screen captures", "Create scrolling captures"],
    notes: "",
    tagIds: [],
    stackIds: ["utilities-stack"],
    pricing: "paid",
    platform: ["desktop"],
    createdDaysAgo: 180,
    useCount: 31,
  },
  {
    title: "Markdown Guide",
    url: "https://markdownguide.org",
    description: "A free reference for Markdown syntax and formatting.",
    categoryId: "learning",
    useCases: ["Look up Markdown syntax", "Learn extended Markdown features"],
    notes: "",
    tagIds: ["markdown"],
    stackIds: ["utilities-stack"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 300,
    useCount: 3,
    archived: true,
  },
  {
    title: "Can I use",
    url: "https://caniuse.com",
    description: "Browser support tables for modern web platform features.",
    categoryId: "dev-frontend",
    useCases: ["Check browser compatibility", "Verify CSS feature support"],
    notes: "",
    tagIds: ["css"],
    stackIds: ["frontend"],
    pricing: "free",
    platform: ["web"],
    createdDaysAgo: 230,
    useCount: 15,
  },
];

export function buildResources(): Resource[] {
  return seeds.map((s, i) => {
    const created = daysAgo(s.createdDaysAgo);
    return {
      id: `res_${i + 1}`,
      title: s.title,
      url: s.url,
      domain: new URL(s.url).hostname.replace(/^www\./, ""),
      description: s.description,
      faviconLetter: s.title.charAt(0).toUpperCase(),
      categoryId: s.categoryId,
      useCases: s.useCases,
      notes: s.notes,
      tagIds: s.tagIds,
      stackIds: s.stackIds,
      pricing: s.pricing,
      platform: s.platform,
      isFavorite: !!s.favorite,
      isArchived: !!s.archived,
      createdAt: created,
      updatedAt: created,
      useCount: s.useCount ?? 0,
      importSource: null,
      importFolder: null,
      importSourceId: null,
      descriptionSource: s.description ? "user" : null,
      usefulForSource: s.useCases.length ? "user" : null,
      enrichmentStatus: "enriched",
      enrichmentAttempts: 0,
      enrichmentAttemptedAt: null,
      needsReviewDismissed: false,
    } satisfies Resource;
  });
}
