-- Categories used to be seeded here as a single shared taxonomy. Since
-- 20260101000005_dynamic_categories.sql, categories are per-user and owned
-- by whoever created them — each new signup gets its own starting set via
-- the public.seed_default_categories() function (called from the
-- handle_new_user trigger), not from this file. Nothing to seed here
-- anymore; kept as a placeholder in case truly global, non-user seed data
-- is ever needed again.
