// Generated by extension/scripts/generate-manifest.js from
// EXTENSION_APP_ORIGINS at build time — DO NOT edit by hand, it will be
// overwritten on the next `npm run build:extension`.
export const DEFAULT_APP_URL = "http://localhost:3000";
